import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class FoodDetailsService {
  constructor() {}
  getFoods(): any[] {
    return [
      {
        id: 1,
        name: 'Indian Breakfast',
        cost: 100,
        imgUrl: 'indian-breakfast.jpg',
        category: 'BreakFast',
      },
      {
        id: 2,
        name: 'Coffee',
        cost: 30,
        imgUrl: 'coffee.png',
        category: 'Breakfast',
      },
      {
        id: 3,
        name: 'Ice Cream',
        cost: 40,
        imgUrl: 'ice-cream.png',
        category: 'Desserts',
      },
      {
        id: 4,
        name: 'Chicken Biriyani',
        cost: 145,
        imgUrl: '/chicken/biriyani.jpg',
        category: 'Chicken',
      },
      {
        id: 5,
        name: 'Mango Juice',
        cost: 50,
        imgUrl: 'mango.png',
        category: 'Juice',
      },
      {
        id: 6,
        name: 'Onion Pakota',
        cost: 30,
        imgUrl: 'onion-pakoda.jpg',
        category: 'Starter',
      },
      {
        id: 7,
        name: 'Fruit Salad',
        cost: 70,
        imgUrl: 'fruit-salad.jpeg',
        category: 'Breakfast',
      },
      {
        id: 8,
        name: 'Chicken Sukka',
        cost: 125,
        imgUrl: '/chicken/sukka.jpg',
        category: 'Chicken',
      },
      {
        id: 9,
        name: 'Meals',
        cost: 150,
        imgUrl: 'Full-meals.jpg',
        category: 'Lunch',
      },
      {
        id: 10,
        name: 'Briyani',
        cost: 180,
        imgUrl: 'biriyani.jpg',
        category: 'Lunch',
      },
      {
        id: 11,
        name: 'Dosa',
        cost: 50,
        imgUrl: 'dosa.jpg',
        category: 'Breakfast',
      },
      {
        id: 12,
        name: 'Apple Juice',
        cost: 50,
        imgUrl: 'apple.png',
        category: 'Juice',
      },
      {
        id: 13,
        name: 'Choco Puffs',
        cost: 80,
        imgUrl: 'chocho-puffs.png',
        category: 'Desserts',
      },
      {
        id: 14,
        name: 'Watermeleon Juice',
        cost: 50,
        imgUrl: 'watermeleon.png',
        category: 'Juice',
      },
      {
        id: 15,
        name: 'Indian Combo Breakfast',
        cost: 75,
        imgUrl: '/Breakfast/indian-combo-breakfast.jpg',
        category: 'BreakFast',
      },
      {
        id: 16,
        name: 'Egg Fried Rice',
        cost: 110,
        imgUrl: '/fried-rice/egg-rice.jpg',
        category: 'FriedRice',
      },
      {
        id: 17,
        name: 'Butter Chicken',
        cost: 150,
        imgUrl: '/chicken/butter-chicken.jpg',
        category: 'Chicken',
      },
      {
        id: 18,
        name: 'Brown Rice Idli',
        cost: 110,
        imgUrl: '/idli/brown-rice-idli.jpg',
        category: 'Idli',
      },
      {
        id: 19,
        name: 'Cholam Idli',
        cost: 120,
        imgUrl: '/idli/cholam-idli.jpg',
        category: 'Idli',
      },
      {
        id: 20,
        name: 'Ghee Roast',
        cost: 145,
        imgUrl: '/dosa/ghee-roast.jpg',
        category: 'Dosa',
      },
      {
        id: 21,
        name: 'Vegetable Burger',
        cost: 125,
        imgUrl: '/burger/ver-burger.jpg',
        category: 'Burger',
      },
      {
        id: 22,
        name: 'Kambu Idli',
        cost: 110,
        imgUrl: '/idli/kambu-idli.jpg',
        category: 'Idli',
      },
      {
        id: 23,
        name: 'Burger and French Fries',
        cost: 85,
        imgUrl: '/Lunch/burger-and-french-fries.jpg',
        category: 'Lunch',
      },
      {
        id: 24,
        name: 'Shusi',
        cost: 60,
        imgUrl: '/Desserts/shusi.jpg',
        category: 'Desserts',
      },
      {
        id: 25,
        name: 'Kanjipuram Idli',
        cost: 110,
        imgUrl: '/idli/kanjipuram-idli.jpg',
        category: 'Idli',
      },
      {
        id: 26,
        name: 'Oats Idli',
        cost: 120,
        imgUrl: '/idli/oats-idli.jpg',
        category: 'Idli',
      },
      {
        id: 27,
        name: 'Adai Dosa',
        cost: 95,
        imgUrl: '/dosa/adai-dosa.jpg',
        category: 'Dosa',
      },
      {
        id: 28,
        name: 'Burger',
        cost: 65,
        imgUrl: '/Lunch/burgur.jpg',
        category: 'Lunch',
      },
      {
        id: 29,
        name: 'Parotta',
        cost: 50,
        imgUrl: '/Lunch/parotta.jpg',
        category: 'Lunch',
      },
      {
        id: 30,
        name: 'Chicken 65',
        cost: 100,
        imgUrl: '/chicken/ch-65.jpg',
        category: 'Chicken',
      },
      {
        id: 31,
        name: 'Ragi Idli',
        cost: 130,
        imgUrl: '/idli/ragi-idli.jpg',
        category: 'Idli',
      },
      {
        id: 32,
        name: 'Carrot-Beetroot Dosa',
        cost: 95,
        imgUrl: '/dosa/carrot-beetroot-dosa.jpg',
        category: 'Dosa',
      },
      {
        id: 33,
        name: 'Idly',
        cost: 50,
        imgUrl: '/Breakfast/idly.jpg',
        category: 'BreakFast',
      },
      {
        id: 34,
        name: 'Chicken Fried Rice',
        cost: 140,
        imgUrl: '/fried-rice/chicken-rice.jpg',
        category: 'FriedRice',
      },
      {
        id: 35,
        name: 'Carrot Halwa',
        cost: 90,
        imgUrl: '/Desserts/carrot-halwa.jpg',
        category: 'Desserts',
      },
      {
        id: 36,
        name: 'Rava Idli',
        cost: 100,
        imgUrl: '/idli/rava-idli.jpg',
        category: 'Idli',
      },
      {
        id: 37,
        name: 'Chicken Pizza',
        cost: 130,
        imgUrl: '/Lunch/chicken-pizza.jpg',
        category: 'Lunch',
      },
      {
        id: 38,
        name: 'Regular Dosa',
        cost: 60,
        imgUrl: '/Breakfast/regular-dosa.jpg',
        category: 'BreakFast',
      },
      {
        id: 39,
        name: 'Thatte Idli',
        cost: 90,
        imgUrl: '/idli/thatte-idli.jpg',
        category: 'Idli',
      },
      {
        id: 40,
        name: 'Varagu Idli',
        cost: 110,
        imgUrl: '/idli/varagu-idli.jpg',
        category: 'Idli',
      },
      {
        id: 41,
        name: 'Chicken curry',
        cost: 130,
        imgUrl: '/chicken/curry.jpg',
        category: 'Chicken',
      },
      {
        id: 42,
        name: 'Shezwan Fried Rice',
        cost: 160,
        imgUrl: '/fried-rice/shezwan-rice.jpg',
        category: 'FriedRice',
      },
      {
        id: 43,
        name: 'Mushroom Burger',
        cost: 145,
        imgUrl: '/burger/mushroom-burger.jpg',
        category: 'Burger',
      },
      {
        id: 44,
        name: 'Channa Curry',
        cost: 95,
        imgUrl: '/Lunch/channa-curry.jpg',
        category: 'Lunch',
      },
      {
        id: 45,
        name: 'Apple juice',
        cost: 55,
        imgUrl: '/juices/green-apple.jpg',
        category: 'Juice',
      },
      {
        id: 46,
        name: 'Healthy Green Dosa',
        cost: 125,
        imgUrl: '/dosa/healthy-green dosa.jpg',
        category: 'Dosa',
      },
      {
        id: 47,
        name: 'Garlic Pizza',
        cost: 110,
        imgUrl: '/Lunch/Garlic-pizza.jpg',
        category: 'Lunch',
      },
      {
        id: 48,
        name: 'Vegetable Fried Rice',
        cost: 120,
        imgUrl: '/fried-rice/veg-rice.jpg',
        category: 'FriedRice',
      },
      {
        id: 49,
        name: 'Cheese Pizza',
        cost: 120,
        imgUrl: '/pizza/cheese-pizza.jpg',
        category: 'Pizza',
      },
      {
        id: 50,
        name: 'Omlete',
        cost: 20,
        imgUrl: '/Lunch/omlete.jpg',
        category: 'Lunch',
      },
      {
        id: 51,
        name: 'Chinese Cheese Cake',
        cost: 120,
        imgUrl: '/Desserts/chinese-cheese-cake.jpg',
        category: 'Desserts',
      },
      {
        id: 52,
        name: 'Masala Dosa',
        cost: 100,
        imgUrl: '/Breakfast/masala-dosa.png',
        category: 'BreakFast',
      },
      {
        id: 53,
        name: 'Chicken Pizza',
        cost: 160,
        imgUrl: '/pizza/chicken-pizza.jpg',
        category: 'Pizza',
      },
      {
        id: 54,
        name: 'Masala Dosa',
        cost: 135,
        imgUrl: '/dosa/masala-dosa.jpg',
        category: 'Dosa',
      },
      {
        id: 55,
        name: 'Chinese Box Noodles',
        cost: 60,
        imgUrl: '/Lunch/chinese-box-noodles.jpg',
        category: 'Lunch',
      },
      {
        id: 56,
        name: 'Garlic Pizza',
        cost: 110,
        imgUrl: '/pizza/Garlic-pizza.jpg',
        category: 'Pizza',
      },
      {
        id: 57,
        name: 'Mushroom Pizza',
        cost: 130,
        imgUrl: '/pizza/mushroom-pizza.jpg',
        category: 'Pizza',
      },
      {
        id: 58,
        name: 'Onion Pizza',
        cost: 110,
        imgUrl: '/Lunch/onion-pizza.jpg',
        category: 'Lunch',
      },
      {
        id: 59,
        name: 'Onion Pizza',
        cost: 125,
        imgUrl: '/pizza/onion-pizza.jpg',
        category: 'Pizza',
      },
      {
        id: 60,
        name: 'Vegetable Pizza',
        cost: 120,
        imgUrl: '/pizza/veg-pizza.jpg',
        category: 'Pizza',
      },
      {
        id: 61,
        name: 'Avacado juice',
        cost: 65,
        imgUrl: '/juices/avacdo.jpg',
        category: 'Juice',
      },
      {
        id: 62,
        name: 'onion Dosa',
        cost: 80,
        imgUrl: '/dosa/onion-dosa.jpg',
        category: 'Dosa',
      },
      {
        id: 63,
        name: 'Chocolate Cake',
        cost: 130,
        imgUrl: '/Desserts/chocolate-cake.jpg',
        category: 'Desserts',
      },
      {
        id: 64,
        name: 'Dosa Ghee Roast',
        cost: 120,
        imgUrl: '/Breakfast/dosa-ghee-roast.jpg',
        category: 'BreakFast',
      },
      {
        id: 65,
        name: 'Dhal Curry',
        cost: 80,
        imgUrl: '/Lunch/dhal-curry.jpg',
        category: 'Lunch',
      },
      {
        id: 67,
        name: 'Podi Dosa',
        cost: 95,
        imgUrl: '/dosa/podi-dosa.jpg',
        category: 'Dosa',
      },
      {
        id: 68,
        name: 'Mango juice',
        cost: 55,
        imgUrl: '/juices/mango-juice.jpg',
        category: 'Juice',
      },
      {
        id: 69,
        name: 'Cookies',
        cost: 75,
        imgUrl: '/Desserts/cookies.jpg',
        category: 'Desserts',
      },
      {
        id: 70,
        name: 'Mint Ginger juice',
        cost: 60,
        imgUrl: '/juices/mint-ginger.jpg',
        category: 'Juice',
      },
      {
        id: 71,
        name: 'Ragi Dosa',
        cost: 100,
        imgUrl: '/dosa/ragi-dosa.jpg',
        category: 'Dosa',
      },
      {
        id: 72,
        name: 'French Fries',
        cost: 70,
        imgUrl: '/Lunch/french-fires.jpg',
        category: 'Lunch',
      },
      {
        id: 73,
        name: 'Chicken Grilled',
        cost: 210,
        imgUrl: '/chicken/grilled.jpg',
        category: 'Chicken',
      },
      {
        id: 74,
        name: 'Poori',
        cost: 70,
        imgUrl: '/Breakfast/poori.jpg',
        category: 'BreakFast',
      },
      {
        id: 75,
        name: 'Meat Burger',
        cost: 175,
        imgUrl: '/burger/meat-burger.jpg',
        category: 'Burger',
      },
      {
        id: 76,
        name: 'Mushroom Pizza',
        cost: 150,
        imgUrl: '/Lunch/mushroom-pizza.jpg',
        category: 'Lunch',
      },
      {
        id: 77,
        name: 'KFG Chicken ',
        cost: 175,
        imgUrl: '/chicken/kfg-fry.jpg',
        category: 'Chicken',
      },
      {
        id: 78,
        name: 'Cupcakes',
        cost: 90,
        imgUrl: '/Desserts/cupcakes.jpg',
        category: 'Desserts',
      },
      {
        id: 79,
        name: 'Rava Dosa',
        cost: 110,
        imgUrl: '/dosa/rava-dosa.jpg',
        category: 'Dosa',
      },
      {
        id: 80,
        name: 'Marraige Meals',
        cost: 130,
        imgUrl: '/Lunch/marriage-meals.jpg',
        category: 'Lunch',
      },
      {
        id: 81,
        name: 'Orange juice',
        cost: 55,
        imgUrl: '/juices/orange.jpg',
        category: 'Juice',
      },
      {
        id: 82,
        name: 'Vegetable Pizza',
        cost: 100,
        imgUrl: '/Lunch/veg-pizza.jpg',
        category: 'Lunch',
      },
      {
        id: 83,
        name: 'Pongal',
        cost: 50,
        imgUrl: '/Breakfast/pongal.jpg',
        category: 'BreakFast',
      },
      {
        id: 84,
        name: 'Gulab Jamun',
        cost: 50,
        imgUrl: '/Desserts/gulab-jamun.jpg',
        category: 'Desserts',
      },
      {
        id: 85,
        name: 'Chicken Leg Pieces',
        cost: 160,
        imgUrl: '/chicken/leg-pices.jpg',
        category: 'Chicken',
      },
      {
        id: 86,
        name: 'Uthappam',
        cost: 60,
        imgUrl: '/dosa/uthappam.jpg',
        category: 'Dosa',
      },
      {
        id: 87,
        name: 'Gulfi',
        cost: 55,
        imgUrl: '/Desserts/gulfi.jpg',
        category: 'Desserts',
      },
      {
        id: 88,
        name: 'Pomogranate juice',
        cost: 75,
        imgUrl: '/juices/pomograte.jpg',
        category: 'Juice',
      },
      {
        id: 89,
        name: 'Wheat Dosa',
        cost: 60,
        imgUrl: '/dosa/wheat-dosa.jpg',
        category: 'Dosa',
      },
      {
        id: 90,
        name: 'Puttu',
        cost: 30,
        imgUrl: '/Breakfast/puttu.jpg',
        category: 'BreakFast',
      },
      {
        id: 91,
        name: 'Halwa',
        cost: 80,
        imgUrl: '/Desserts/halwa.jpg',
        category: 'Desserts',
      },
      {
        id: 92,
        name: 'Soda',
        cost: 45,
        imgUrl: '/juices/soda.jpg',
        category: 'Juice',
      },
      {
        id: 93,
        name: 'Raagi Dosa',
        cost: 80,
        imgUrl: '/Breakfast/Ragi-dosa.jpg',
        category: 'BreakFast',
      },
      {
        id: 94,
        name: 'Mochi',
        cost: 60,
        imgUrl: '/Desserts/mochi.jpg',
        category: 'Desserts',
      },
      {
        id: 95,
        name: 'Chicken Pepper Fry',
        cost: 145,
        imgUrl: '/chicken/pepper-fry.jpg',
        category: 'Chicken',
      },
      {
        id: 96,
        name: 'Roti',
        cost: 60,
        imgUrl: '/Breakfast/Rootti.jpg',
        category: 'BreakFast',
      },
      {
        id: 97,
        name: 'Rasamalai',
        cost: 70,
        imgUrl: '/Desserts/rasmalai.jpg',
        category: 'Desserts',
      },
      {
        id: 98,
        name: 'Cucumber juice',
        cost: 45,
        imgUrl: '/juices/cucumber-juice.jpg',
        category: 'Juice',
      },
      {
        id: 99,
        name: 'Pav Bhaji',
        cost: 110,
        imgUrl: '/starters/pav-bhaji.jpg',
        category: 'Starters',
      },
      {
        id: 100,
        name: 'Chicken Thanthuri',
        cost: 195,
        imgUrl: '/chicken/thanthuri.jpg',
        category: 'Chicken',
      },
      {
        id: 101,
        name: 'Upma',
        cost: 45,
        imgUrl: '/Breakfast/Upma.jpg',
        category: 'BreakFast',
      },
      {
        id: 102,
        name: 'lemon juice',
        cost: 35,
        imgUrl: '/juices/lime-juice.jpg',
        category: 'Juice',
      },
      {
        id: 103,
        name: 'Dinner Meals',
        cost: 70,
        imgUrl: '/dinner/dinner-meals.jpg',
        category: 'Dinner',
      },
      {
        id: 104,
        name: 'Idli',
        cost: 40,
        imgUrl: '/dinner/idly.jpg',
        category: 'Dinner',
      },
      {
        id: 105,
        name: 'Uthappam',
        cost: 50,
        imgUrl: '/dinner/uthappam.jpg',
        category: 'Dinner',
      },
      {
        id: 106,
        name: 'Parotta',
        cost: 50,
        imgUrl: '/Lunch/parotta.jpg',
        category: 'Dinner',
      },
      {
        id: 107,
        name: 'Chicken Burger',
        cost: 155,
        imgUrl: '/burger/chicken-burger.jpg',
        category: 'Burger',
      },

      {
        id: 108,
        name: 'Grilled Shrimp',
        cost: 90,
        imgUrl: '/starters/grilled-shrimp.jpg',
        category: 'Starters',
      },
      {
        id: 109,
        name: 'Semya',
        cost: 55,
        imgUrl: '/Breakfast/semya-upma.jpg',
        category: 'BreakFast',
      },
      {
        id: 110,
        name: 'Fulka',
        cost: 75,
        imgUrl: '/dinner/fulka.jpg',
        category: 'Dinner',
      },
      {
        id: 111,
        name: 'Sweet Mixed',
        cost: 75,
        imgUrl: '/Desserts/sweet-mixed.jpg',
        category: 'Desserts',
      },
      {
        id: 112,
        name: 'Cheese Pizza',
        cost: 90,
        imgUrl: '/Desserts/cheese-pizza.jpg',
        category: 'Desserts',
      },
      {
        id: 113,
        name: 'Idiyappam',
        cost: 75,
        imgUrl: '/Breakfast/idiyaappam.jpg',
        category: 'Breakfast',
      },
      {
        id: 114,
        name: 'Walnut Chicket Brest Egg',
        cost: 110,
        imgUrl: '/Desserts/walnut-chicken-breast-egg.jpg',
        category: 'Desserts',
      },
      {
        id: 115,
        name: 'Grilled Skewers',
        cost: 100,
        imgUrl: '/starters/grilled-skewers.jpg',
        category: 'Starters',
      },
      {
        id: 116,
        name: 'Vada',
        cost: 15,
        imgUrl: '/Breakfast/vada.jpg',
        category: 'BreakFast',
      },
      {
        id: 117,
        name: 'Chocolate Pudding',
        cost: 95,
        imgUrl: '/Desserts/chocolate-pudding.jpg',
        category: 'Desserts',
      },
      {
        id: 118,
        name: 'Chapathi with Chicken',
        cost: 140,
        imgUrl: '/Breakfast/chapathi-with-chicken.png',
        category: 'Breakfast',
      },
      {
        id: 119,
        name: 'Dry Laddu',
        cost: 65,
        imgUrl: '/Desserts/dry-laddu.jpg',
        category: 'Desserts',
      },
      {
        id: 120,
        name: 'Chinese Soup Noodles',
        cost: 130,
        imgUrl: '/Lunch/chinese-soap-noodles.jpg',
        category: 'Lunch',
      },
      {
        id: 121,
        name: 'Bean Burger',
        cost: 125,
        imgUrl: '/burger/bean-burger.jpg',
        category: 'Burger',
      },
      {
        id: 122,
        name: 'Chinese noodles',
        cost: 100,
        imgUrl: '/Lunch/chinese-noodles.jpg',
        category: 'Lunch',
      },
      {
        id: 123,
        name: 'Japanese Breakfast Large',
        cost: 170,
        imgUrl: '/Breakfast/japanese-breakfast-large.jpg',
        category: 'Breakfast',
      },
      {
        id: 124,
        name: 'Fried Chicken',
        cost: 60,
        imgUrl: '/starters/fried-chicken.jpg',
        category: 'Starters',
      },
      {
        id: 125,
        name: 'Spicy Pasta',
        cost: 100,
        imgUrl: '/Lunch/spicy-pasta.jpg',
        category: 'Lunch',
      },
      {
        id: 126,
        name: 'Kaju Katli',
        cost: 95,
        imgUrl: '/Desserts/kaju-katli.jpg',
        category: 'Desserts',
      },
      {
        id: 127,
        name: 'Pudding',
        cost: 70,
        imgUrl: '/starters/pudding.jpg',
        category: 'Starters',
      },
      {
        id: 128,
        name: 'Panner Butter Masala',
        cost: 85,
        imgUrl: '/Lunch/panner-butter-masala.jpg',
        category: 'Lunch',
      },
      {
        id: 129,
        name: 'Japanese Breakfast Small',
        cost: 80,
        imgUrl: '/Breakfast/japanese-breakfast-small.jpg',
        category: 'Breakfast',
      },
      {
        id: 130,
        name: 'Dhal Salad',
        cost: 80,
        imgUrl: '/Breakfast/dhal-salad.jpg',
        category: 'Breakfast',
      },
      {
        id: 131,
        name: 'Fish Fry',
        cost: 120,
        imgUrl: '/Lunch/fish-fry.jpg',
        category: 'Lunch',
      },
      {
        id: 132,
        name: 'Japanese Breakfast Small',
        cost: 80,
        imgUrl: '/Breakfast/japanese-breakfast-small.jpg',
        category: 'Breakfast',
      },
      {
        id: 133,
        name: 'Non Veg Large Meal',
        cost: 180,
        imgUrl: '/Lunch/non-veg-large-meal.jpg',
        category: 'Lunch',
      },
      {
        id: 134,
        name: 'Samosa',
        cost: 40,
        imgUrl: '/starters/samosa.jpg',
        category: 'Starters',
      },
      {
        id: 135,
        name: 'Apple Salad',
        cost: 80,
        imgUrl: '/Breakfast/apple-salad.jpg',
        category: 'BreakFast',
      },
      {
        id: 136,
        name: 'Avacado Walnut Salad',
        cost: 90,
        imgUrl: '/Breakfast/avacado-walnut-salad.jpg',
        category: 'BreakFast',
      },
      {
        id: 137,
        name: 'Red Gabbage Salad',
        cost: 90,
        imgUrl: '/Breakfast/red-gabbage-salad.jpg',
        category: 'BreakFast',
      },
      {
        id: 138,
        name: 'Simple Pulao',
        cost: 90,
        imgUrl: '/Lunch/simple-pulao.jpg',
        category: 'Lunch',
      },
      {
        id: 139,
        name: 'Cheese Burger',
        cost: 125,
        imgUrl: '/burger/cheese-burger.jpg',
        category: 'Burger',
      },
      {
        id: 140,
        name: 'Strawberry Salad',
        cost: 80,
        imgUrl: '/Breakfast/Strawberry-salad.jpg',
        category: 'BreakFast',
      },
      {
        id: 141,
        name: 'Tangariene Spinach Salad',
        cost: 80,
        imgUrl: '/Breakfast/tangaries-spinach-walnut salad.jpg',
        category: 'BreakFast',
      },
      {
        id: 142,
        name: 'Sandwich',
        cost: 55,
        imgUrl: '/Lunch/Sandwish.jpg',
        category: 'Lunch',
      },
      {
        id: 143,
        name: 'Rice with Shrimp',
        cost: 110,
        imgUrl: '/Lunch/rice-with-shrimp.jpg',
        category: 'Lunch',
      },
      {
        id: 144,
        name: 'Beef Bao Buns',
        cost: 90,
        imgUrl: '/starters/Beef-Bao-Buns.jpg',
        category: 'Starters',
      },
      {
        id: 145,
        name: 'Chilli Panner',
        cost: 95,
        imgUrl: '/starters/chilli-panner.jpg',
        category: 'Starters',
      },
      {
        id: 146,
        name: 'Corn Chips',
        cost: 85,
        imgUrl: '/starters/corn-chips.jpg',
        category: 'Starters',
      },
      {
        id: 147,
        name: 'MoMos',
        cost: 95,
        imgUrl: '/starters/momos.jpg',
        category: 'Starters',
      },
      {
        id: 148,
        name: 'Chicken Biriyani',
        cost: 155,
        imgUrl: '/Biriyani/Chicken-Biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 149,
        name: 'Dindukkal Biriyani',
        cost: 200,
        imgUrl: '/Biriyani/Chicken-Biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 150,
        name: 'Mutton Biriyani',
        cost: 195,
        imgUrl: '/Biriyani/mutton-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 151,
        name: 'Egg Biriyani',
        cost: 120,
        imgUrl: '/Biriyani/egg-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 152,
        name: 'Fish Biriyani',
        cost: 140,
        imgUrl: '/Biriyani/fish-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 153,
        name: 'Hyderabad Biriyani',
        cost: 160,
        imgUrl: '/Biriyani/hyderabad-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 154,
        name: 'Mushroom Biriyani',
        cost: 145,
        imgUrl: '/Biriyani/mushroom-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 155,
        name: 'Paneer Biriyani',
        cost: 150,
        imgUrl: '/Biriyani/panner-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 156,
        name: 'Soyya Biriyani',
        cost: 125,
        imgUrl: '/Biriyani/soyya-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 157,
        name: 'Prawn Biriyani',
        cost: 145,
        imgUrl: '/Biriyani/prawn-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        id: 158,
        name: 'Vegetable Biriyani',
        cost: 110,
        imgUrl: '/Biriyani/veg-biriyani.jpg',
        category: 'Biriyani',
      },
    ];
  }
}
