import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class FoodDetailsService {
  constructor() {}
  getFoods(): any[] {
    return [
      {
        name: 'Indian Breakfast',
        cost: '100',
        imgUrl: 'indian-breakfast.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Coffee',
        cost: '30',
        imgUrl: 'coffee.png',
        category: 'Breakfast',
      },
      {
        name: 'Ice Cream',
        cost: '40',
        imgUrl: 'ice-cream.png',
        category: 'Desserts',
      },
      {
        name: 'Chicken Biriyani',
        cost: '145',
        imgUrl: '/chicken/biriyani.jpg',
        category: 'Chicken',
      },
      {
        name: 'Mango Juice',
        cost: '50',
        imgUrl: 'mango.png',
        category: 'Juice',
      },
      {
        name: 'Onion Pakota',
        cost: '30',
        imgUrl: 'onion-pakoda.jpg',
        category: 'Starter',
      },
      {
        name: 'Fruit Salad',
        cost: '70',
        imgUrl: 'fruit-salad.jpeg',
        category: 'Breakfast',
      },
      {
        name: 'Chicken Sukka',
        cost: '125',
        imgUrl: '/chicken/sukka.jpg',
        category: 'Chicken',
      },
      {
        name: 'Meals',
        cost: '150',
        imgUrl: 'Full-meals.jpg',
        category: 'Lunch',
      },
      {
        name: 'Briyani',
        cost: '180',
        imgUrl: 'biriyani.jpg',
        category: 'Lunch',
      },
      { name: 'Dosa', cost: '50', imgUrl: 'dosa.jpg', category: 'Breakfast' },
      {
        name: 'Apple Juice',
        cost: '50',
        imgUrl: 'apple.png',
        category: 'Juice',
      },
      {
        name: 'Choco Puffs',
        cost: '80',
        imgUrl: 'chocho-puffs.png',
        category: 'Desserts',
      },
      {
        name: 'Watermeleon Juice',
        cost: '50',
        imgUrl: 'watermeleon.png',
        category: 'Juice',
      },
      {
        name: 'Indian Combo Breakfast',
        cost: '75',
        imgUrl: '/Breakfast/indian-combo-breakfast.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Egg Fried Rice',
        cost: '110',
        imgUrl: '/fried-rice/egg-rice.jpg',
        category: 'FriedRice',
      },
      {
        name: 'Butter Chicken',
        cost: '150',
        imgUrl: '/chicken/butter-chicken.jpg',
        category: 'Chicken',
      },
      {
        name: 'Brown Rice Idli',
        cost: '110',
        imgUrl: '/idli/brown-rice-idli.jpg',
        category: 'Idli',
      },
      {
        name: 'Cholam Idli',
        cost: '120',
        imgUrl: '/idli/cholam-idli.jpg',
        category: 'Idli',
      },
      {
        name: 'Ghee Roast',
        cost: '145',
        imgUrl: '/dosa/ghee-roast.jpg',
        category: 'Dosa',
      },
      {
        name: 'Vegetable Burger',
        cost: '125',
        imgUrl: '/burger/ver-burger.jpg',
        category: 'Burger',
      },
      {
        name: 'Kambu Idli',
        cost: '110',
        imgUrl: '/idli/kambu-idli.jpg',
        category: 'Idli',
      },
      {
        name: 'Burger and French Fries',
        cost: '85',
        imgUrl: '/Lunch/burger-and-french-fries.jpg',
        category: 'Lunch',
      },
      {
        name: 'Shusi',
        cost: '60',
        imgUrl: '/Desserts/shusi.jpg',
        category: 'Desserts',
      },
      {
        name: 'Kanjipuram Idli',
        cost: '110',
        imgUrl: '/idli/kanjipuram-idli.jpg',
        category: 'Idli',
      },
      {
        name: 'Oats Idli',
        cost: '120',
        imgUrl: '/idli/oats-idli.jpg',
        category: 'Idli',
      },
      {
        name: 'Adai Dosa',
        cost: '95',
        imgUrl: '/dosa/adai-dosa.jpg',
        category: 'Dosa',
      },
      {
        name: 'Burger',
        cost: '65',
        imgUrl: '/Lunch/burgur.jpg',
        category: 'Lunch',
      },
      {
        name: 'Parotta',
        cost: '50',
        imgUrl: '/Lunch/parotta.jpg',
        category: 'Lunch',
      },
      {
        name: 'Chicken 65',
        cost: '100',
        imgUrl: '/chicken/ch-65.jpg',
        category: 'Chicken',
      },
      {
        name: 'Ragi Idli',
        cost: '130',
        imgUrl: '/idli/ragi-idli.jpg',
        category: 'Idli',
      },
      {
        name: 'Carrot-Beetroot Dosa',
        cost: '95',
        imgUrl: '/dosa/carrot-beetroot-dosa.jpg',
        category: 'Dosa',
      },
      {
        name: 'Idly',
        cost: '50',
        imgUrl: '/Breakfast/idly.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Chicken Fried Rice',
        cost: '140',
        imgUrl: '/fried-rice/chicken-rice.jpg',
        category: 'FriedRice',
      },
      {
        name: 'Carrot Halwa',
        cost: '90',
        imgUrl: '/Desserts/carrot-halwa.jpg',
        category: 'Desserts',
      },
      {
        name: 'Rava Idli',
        cost: '100',
        imgUrl: '/idli/rava-idli.jpg',
        category: 'Idli',
      },
      {
        name: 'Chicken Pizza',
        cost: '130',
        imgUrl: '/Lunch/chicken-pizza.jpg',
        category: 'Lunch',
      },
      {
        name: 'Regular Dosa',
        cost: '60',
        imgUrl: '/Breakfast/regular-dosa.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Thatte Idli',
        cost: '90',
        imgUrl: '/idli/thatte-idli.jpg',
        category: 'Idli',
      },
      {
        name: 'Varagu Idli',
        cost: '110',
        imgUrl: '/idli/varagu-idli.jpg',
        category: 'Idli',
      },
      {
        name: 'Chicken curry',
        cost: '130',
        imgUrl: '/chicken/curry.jpg',
        category: 'Chicken',
      },
      {
        name: 'Shezwan Fried Rice',
        cost: '160',
        imgUrl: '/fried-rice/shezwan-rice.jpg',
        category: 'FriedRice',
      },
      {
        name: 'Mushroom Burger',
        cost: '145',
        imgUrl: '/burger/mushroom-burger.jpg',
        category: 'Burger',
      },
      {
        name: 'Channa Curry',
        cost: '95',
        imgUrl: '/Lunch/channa-curry.jpg',
        category: 'Lunch',
      },
      {
        name: 'Apple juice',
        cost: '55',
        imgUrl: '/juices/green-apple.jpg',
        category: 'Juice',
      },
      {
        name: 'Healthy Green Dosa',
        cost: '125',
        imgUrl: '/dosa/healthy-green dosa.jpg',
        category: 'Dosa',
      },
      {
        name: 'Garlic Pizza',
        cost: '110',
        imgUrl: '/Lunch/Garlic-pizza.jpg',
        category: 'Lunch',
      },
      {
        name: 'Vegetable Fried Rice',
        cost: '120',
        imgUrl: '/fried-rice/veg-rice.jpg',
        category: 'FriedRice',
      },
      {
        name: 'Cheese Pizza',
        cost: '120',
        imgUrl: '/pizza/cheese-pizza.jpg',
        category: 'Pizza',
      },
      {
        name: 'Omlete',
        cost: '20',
        imgUrl: '/Lunch/omlete.jpg',
        category: 'Lunch',
      },
      {
        name: 'Chinese Cheese Cake',
        cost: '120',
        imgUrl: '/Desserts/chinese-cheese-cake.jpg',
        category: 'Desserts',
      },
      {
        name: 'Masala Dosa',
        cost: '100',
        imgUrl: '/Breakfast/masala-dosa.png',
        category: 'BreakFast',
      },
      {
        name: 'Chicken Pizza',
        cost: '160',
        imgUrl: '/pizza/chicken-pizza.jpg',
        category: 'Pizza',
      },
      {
        name: 'Masala Dosa',
        cost: '135',
        imgUrl: '/dosa/masala-dosa.jpg',
        category: 'Dosa',
      },
      {
        name: 'Chinese Box Noodles',
        cost: '60',
        imgUrl: '/Lunch/chinese-box-noodles.jpg',
        category: 'Lunch',
      },
      {
        name: 'Garlic Pizza',
        cost: '110',
        imgUrl: '/pizza/Garlic-pizza.jpg',
        category: 'Pizza',
      },
      {
        name: 'Mushroom Pizza',
        cost: '130',
        imgUrl: '/pizza/mushroom-pizza.jpg',
        category: 'Pizza',
      },
      {
        name: 'Onion Pizza',
        cost: '110',
        imgUrl: '/Lunch/onion-pizza.jpg',
        category: 'Lunch',
      },
      {
        name: 'Onion Pizza',
        cost: '125',
        imgUrl: '/pizza/onion-pizza.jpg',
        category: 'Pizza',
      },
      {
        name: 'Vegetable Pizza',
        cost: '120',
        imgUrl: '/pizza/veg-pizza.jpg',
        category: 'Pizza',
      },
      {
        name: 'Avacado juice',
        cost: '65',
        imgUrl: '/juices/avacdo.jpg',
        category: 'Juice',
      },
      {
        name: 'onion Dosa',
        cost: '80',
        imgUrl: '/dosa/onion-dosa.jpg',
        category: 'Dosa',
      },
      {
        name: 'Chocolate Cake',
        cost: '130',
        imgUrl: '/Desserts/chocolate-cake.jpg',
        category: 'Desserts',
      },
      {
        name: 'Dosa Ghee Roast',
        cost: '120',
        imgUrl: '/Breakfast/dosa-ghee-roast.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Dhal Curry',
        cost: '80',
        imgUrl: '/Lunch/dhal-curry.jpg',
        category: 'Lunch',
      },
      {
        name: 'Podi Dosa',
        cost: '95',
        imgUrl: '/dosa/podi-dosa.jpg',
        category: 'Dosa',
      },
      {
        name: 'Mango juice',
        cost: '55',
        imgUrl: '/juices/mango-juice.jpg',
        category: 'Juice',
      },
      {
        name: 'Cookies',
        cost: '75',
        imgUrl: '/Desserts/cookies.jpg',
        category: 'Desserts',
      },
      {
        name: 'Mint Ginger juice',
        cost: '60',
        imgUrl: '/juices/mint-ginger.jpg',
        category: 'Juice',
      },
      {
        name: 'Ragi Dosa',
        cost: '100',
        imgUrl: '/dosa/ragi-dosa.jpg',
        category: 'Dosa',
      },
      {
        name: 'French Fries',
        cost: '70',
        imgUrl: '/Lunch/french-fires.jpg',
        category: 'Lunch',
      },
      {
        name: 'Chicken Grilled',
        cost: '210',
        imgUrl: '/chicken/grilled.jpg',
        category: 'Chicken',
      },
      {
        name: 'Poori',
        cost: '70',
        imgUrl: '/Breakfast/poori.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Meat Burger',
        cost: '175',
        imgUrl: '/burger/meat-burger.jpg',
        category: 'Burger',
      },
      {
        name: 'Mushroom Pizza',
        cost: '150',
        imgUrl: '/Lunch/mushroom-pizza.jpg',
        category: 'Lunch',
      },
      {
        name: 'KFG Chicken ',
        cost: '175',
        imgUrl: '/chicken/kfg-fry.jpg',
        category: 'Chicken',
      },
      {
        name: 'Cupcakes',
        cost: '90',
        imgUrl: '/Desserts/cupcakes.jpg',
        category: 'Desserts',
      },
      {
        name: 'Rava Dosa',
        cost: '110',
        imgUrl: '/dosa/rava-dosa.jpg',
        category: 'Dosa',
      },
      {
        name: 'Marraige Meals',
        cost: '130',
        imgUrl: '/Lunch/marriage-meals.jpg',
        category: 'Lunch',
      },
      {
        name: 'Orange juice',
        cost: '55',
        imgUrl: '/juices/orange.jpg',
        category: 'Juice',
      },
      {
        name: 'Vegetable Pizza',
        cost: '100',
        imgUrl: '/Lunch/veg-pizza.jpg',
        category: 'Lunch',
      },
      {
        name: 'Pongal',
        cost: '50',
        imgUrl: '/Breakfast/pongal.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Gulab Jamun',
        cost: '50',
        imgUrl: '/Desserts/gulab-jamun.jpg',
        category: 'Desserts',
      },
      {
        name: 'Chicken Leg Pieces',
        cost: '160',
        imgUrl: '/chicken/leg-pices.jpg',
        category: 'Chicken',
      },
      {
        name: 'Uthappam',
        cost: '60',
        imgUrl: '/dosa/uthappam.jpg',
        category: 'Dosa',
      },
      {
        name: 'Gulfi',
        cost: '55',
        imgUrl: '/Desserts/gulfi.jpg',
        category: 'Desserts',
      },
      {
        name: 'Pomogranate juice',
        cost: '75',
        imgUrl: '/juices/pomograte.jpg',
        category: 'Juice',
      },
      {
        name: 'Wheat Dosa',
        cost: '60',
        imgUrl: '/dosa/wheat-dosa.jpg',
        category: 'Dosa',
      },
      {
        name: 'Puttu',
        cost: '30',
        imgUrl: '/Breakfast/puttu.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Halwa',
        cost: '80',
        imgUrl: '/Desserts/halwa.jpg',
        category: 'Desserts',
      },
      {
        name: 'Soda',
        cost: '45',
        imgUrl: '/juices/soda.jpg',
        category: 'Juice',
      },
      {
        name: 'Raagi Dosa',
        cost: '80',
        imgUrl: '/Breakfast/Ragi-dosa.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Mochi',
        cost: '60',
        imgUrl: '/Desserts/mochi.jpg',
        category: 'Desserts',
      },
      {
        name: 'Chicken Pepper Fry',
        cost: '145',
        imgUrl: '/chicken/pepper-fry.jpg',
        category: 'Chicken',
      },
      {
        name: 'Roti',
        cost: '60',
        imgUrl: '/Breakfast/Rootti.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Rasamalai',
        cost: '70',
        imgUrl: '/Desserts/rasmalai.jpg',
        category: 'Desserts',
      },
      {
        name: 'Cucumber juice',
        cost: '45',
        imgUrl: '/juices/cucumber-juice.jpg',
        category: 'Juice',
      },
      {
        name: 'Pav Bhaji',
        cost: '110',
        imgUrl: '/starters/pav-bhaji.jpg',
        category: 'Starters',
      },
      {
        name: 'Chicken Thanthuri',
        cost: '195',
        imgUrl: '/chicken/thanthuri.jpg',
        category: 'Chicken',
      },
      {
        name: 'Upma',
        cost: '45',
        imgUrl: '/Breakfast/Upma.jpg',
        category: 'BreakFast',
      },
      {
        name: 'lemon juice',
        cost: '35',
        imgUrl: '/juices/lime-juice.jpg',
        category: 'Juice',
      },
      {
        name: 'Dinner Meals',
        cost: '70',
        imgUrl: '/dinner/dinner-meals.jpg',
        category: 'Dinner',
      },
      {
        name: 'Idli',
        cost: '40',
        imgUrl: '/dinner/idly.jpg',
        category: 'Dinner',
      },
      {
        name: 'Uthappam',
        cost: '50',
        imgUrl: '/dinner/uthappam.jpg',
        category: 'Dinner',
      },
      {
        name: 'Parotta',
        cost: '50',
        imgUrl: '/Lunch/parotta.jpg',
        category: 'Dinner',
      },
      {
        name: 'Chicken Burger',
        cost: '155',
        imgUrl: '/burger/chicken-burger.jpg',
        category: 'Burger',
      },
      {
        name: 'Strawberry Pie',
        cost: '100',
        imgUrl: '/Desserts/strawberry-pie-mini.jpg',
        category: 'Desserts',
      },
      {
        name: 'Grape juice',
        cost: '55',
        imgUrl: '/juices/grape-red.jpg',
        category: 'Juice',
      },
      {
        name: 'Grilled Shrimp',
        cost: '90',
        imgUrl: '/starters/grilled-shrimp.jpg',
        category: 'Starters'
      },
      {
        name: 'Semya',
        cost: '55',
        imgUrl: '/Breakfast/semya-upma.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Fulka',
        cost: '75',
        imgUrl: '/dinner/fulka.jpg',
        category: 'Dinner',
      },
      {
        name: 'Sweet Mixed',
        cost: '75',
        imgUrl: '/Desserts/sweet-mixed.jpg',
        category: 'Desserts',
      },
      {
        name: 'Cheese Pizza',
        cost: '90',
        imgUrl: '/Desserts/cheese-pizza.jpg',
        category: 'Desserts',
      },
      {
        name:'Idiyappam',
        cost:'75',
        imgUrl:'/Breakfast/idiyaappam.jpg',
        category:'Breakfast'
      },
      {
        name: 'Walnut Chicket Brest Egg',
        cost: '110',
        imgUrl: '/Desserts/walnut-chicken-breast-egg.jpg',
        category: 'Desserts',
      },
      {
        name: 'Grilled Skewers',
        cost: '100',
        imgUrl: '/starters/grilled-skewers.jpg',
        category: 'Starters',
      },
      {
        name: 'Vada',
        cost: '15',
        imgUrl: '/Breakfast/vada.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Chocolate Pudding',
        cost: '95',
        imgUrl: '/Desserts/chocolate-pudding.jpg',
        category: 'Desserts',
      },
      {
        name:'Chapathi with Chicken',
        cost:'140',
        imgUrl:'/Breakfast/chapathi-with-chicken.png',
        category:'Breakfast'
      },
      {
        name: 'Dry Laddu',
        cost: '65',
        imgUrl: '/Desserts/dry-laddu.jpg',
        category: 'Desserts',
      },
      {
        name: 'Chinese Soup Noodles',
        cost: '130',
        imgUrl: '/Lunch/chinese-soap-noodles.jpg',
        category: 'Lunch',
      },
      {
        name: 'Bean Burger',
        cost: '125',
        imgUrl: '/burger/bean-burger.jpg',
        category: 'Burger',
      },
      {
        name: 'Chinese noodles',
        cost: '100',
        imgUrl: '/Lunch/chinese-noodles.jpg',
        category: 'Lunch',
      },
      {
        name:'Japanese Breakfast Large',
        cost:'170',
        imgUrl:'/Breakfast/japanese-breakfast-large.jpg',
        category:'Breakfast'
      },
      {
        name: 'Fried Chicken',
        cost: '60',
        imgUrl: '/starters/fried-chicken.jpg',
        category: 'Starters',
      },
      {
        name: 'Spicy Pasta',
        cost: '100',
        imgUrl: '/Lunch/spicy-pasta.jpg',
        category: 'Lunch',
      },
      {
        name: 'Kaju Katli',
        cost: '95',
        imgUrl: '/Desserts/kaju-katli.jpg',
        category: 'Desserts',
      },
      {
        name: 'Pudding',
        cost: '70',
        imgUrl: '/starters/pudding.jpg',
        category: 'Starters',
      },
      {
        name: 'Panner Butter Masala',
        cost: '85',
        imgUrl: '/Lunch/panner-butter-masala.jpg',
        category: 'Lunch',
      },
      {
        name:'Japanese Breakfast Small',
        cost:'80',
        imgUrl:'/Breakfast/japanese-breakfast-small.jpg',
        category:'Breakfast'
      },
      {
        name:'Dhal Salad',
        cost:'80',
        imgUrl:'/Breakfast/dhal-salad.jpg',
        category:'Breakfast'
      },
      {
        name: 'Fish Fry',
        cost: '120',
        imgUrl: '/Lunch/fish-fry.jpg',
        category: 'Lunch',
      },
      {
        name:'Japanese Breakfast Small',
        cost:'80',
        imgUrl:'/Breakfast/japanese-breakfast-small.jpg',
        category:'Breakfast'
      },
      {
        name: 'Non Veg Large Meal',
        cost: '180',
        imgUrl: '/Lunch/non-veg-large-meal.jpg',
        category: 'Lunch',
      },
      {
        name: 'Samosa',
        cost: '40',
        imgUrl: '/starters/samosa.jpg',
        category: 'Starters',
      },
      {
        name: 'Apple Salad',
        cost: '80',
        imgUrl: '/Breakfast/apple-salad.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Avacado Walnut Salad',
        cost: '90',
        imgUrl: '/Breakfast/avacado-walnut-salad.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Red Gabbage Salad',
        cost: '90',
        imgUrl: '/Breakfast/red-gabbage-salad.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Simple Pulao',
        cost: '90',
        imgUrl: '/Lunch/simple-pulao.jpg',
        category: 'Lunch',
      },
      {
        name: 'Cheese Burger',
        cost: '125',
        imgUrl: '/burger/cheese-burger.jpg',
        category: 'Burger',
      },
      {
        name: 'Strawberry Salad',
        cost: '80',
        imgUrl: '/Breakfast/Strawberry-salad.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Tangariene Spinach Salad',
        cost: '80',
        imgUrl: '/Breakfast/tangaries-spinach-walnut salad.jpg',
        category: 'BreakFast',
      },
      {
        name: 'Sandwich',
        cost: '55',
        imgUrl: '/Lunch/Sandwish.jpg',
        category: 'Lunch',
      },
      {
        name: 'Rice with Shrimp',
        cost: '110',
        imgUrl: '/Lunch/rice-with-shrimp.jpg',
        category: 'Lunch',
      },
      {
        name: 'Beef Bao Buns',
        cost: '90',
        imgUrl: '/starters/Beef-Bao-Buns.jpg',
        category: 'Starters',
      },
      {
        name: 'Chilli Panner',
        cost: '95',
        imgUrl: '/starters/chilli-panner.jpg',
        category: 'Starters',
      },
      {
        name: 'Corn Chips',
        cost: '85',
        imgUrl: '/starters/corn-chips.jpg',
        category: 'Starters',
      },
      {
        name: 'MoMos',
        cost: '95',
        imgUrl: '/starters/momos.jpg',
        category: 'Starters',
      },
      {
        name: 'Chicken Biriyani',
        cost: '155',
        imgUrl: '/Biriyani/Chicken-Biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Dindukkal Biriyani',
        cost: '200',
        imgUrl: '/Biriyani/Chicken-Biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Mutton Biriyani',
        cost: '195',
        imgUrl: '/Biriyani/mutton-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Egg Biriyani',
        cost: '120',
        imgUrl: '/Biriyani/egg-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Fish Biriyani',
        cost: '140',
        imgUrl: '/Biriyani/fish-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Hyderabad Biriyani',
        cost: '160',
        imgUrl: '/Biriyani/hyderabad-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Mushroom Biriyani',
        cost: '145',
        imgUrl: '/Biriyani/mushroom-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Paneer Biriyani',
        cost: '150',
        imgUrl: '/Biriyani/panner-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Soyya Biriyani',
        cost: '125',
        imgUrl: '/Biriyani/soyya-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Prawn Biriyani',
        cost: '145',
        imgUrl: '/Biriyani/prawn-biriyani.jpg',
        category: 'Biriyani',
      },
      {
        name: 'Vegetable Biriyani',
        cost: '110',
        imgUrl: '/Biriyani/veg-biriyani.jpg',
        category: 'Biriyani',
      },





    ];
  }
}
